### PR TITLE
Fix for https://github.com/Siggen/jaxb2-namespace-prefix/issues/3

### PR DESCRIPTION
**Pull request by solind**
Issue #3

### CODE REVIEW

**Comment by Siggen** [comment]
Thanks for you PR ! I've got a few comments:

1. I think there a problem with the following condition `Set<String> result = new HashSet<String>(uriCountMap == null ? Collections.<String>emptySet() : uriCountMap.keySet());`. If `uriCountMap`is null, you'll store a `Collections.<String>emptySet()` which is immutable into `result`. And then below, you try to add something to `result`: I think it will raise an exception, no ?
2. I prefer to use `final` variables whenever possible: could you turn variables `result`, `methods`, `annotations`, and so on... into final variables ? 

Thanks in advance ! Regards.

**Comment by solind** [comment]
Hello!

1) Actually, the emptySet is not stored anywhere; its members (of which there are none) are used to populate the HashSet<String> result variable, in the event uriCountMap is null.
2) Good idea, I shall do that.

Regards.

**Comment by solind** [comment]
OK I updated the PR...
1) I made what's happening in the initialization of the results HashSet clearer (esp, in the event uriCountMap is null).
2) I made all the single-use variables final.
Cheers!

**Comment by Siggen** [comment]
1. Oh, you're right, I totally overlooked the new hashset creation. Silly me, sorry about that.
2. Perfect, thanks.

**Pull request merged**
